name: Build project
on: [push]
jobs:
  package-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: maven package
        run: |
          mvn package -DskipTests -ntp
      - name: maven test
        run: |
          mvn test
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
